[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    sensirion/Sensirion I2C SCD4x
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays
    knolleary/PubSubClient
